import subprocess
import pytest
from pathlib import Path
import json
import os
import sys
import shutil # For cache cleanup
from unittest.mock import patch # Import patch

# Import the main entry point
from avtools.cli.main import main as avtools_main
from avtools.video.config import get_video_dir, get_video_hash # Add get_video_hash

# Define the path to the test data relative to the tests directory
TEST_DATA_DIR = Path(__file__).parent.parent / "data"
TEST_VIDEO = TEST_DATA_DIR / "music-video.mp4"

# --- Fixtures ---

@pytest.fixture(scope="session")
def test_video_exists():
    """Fixture to ensure the test video file exists."""
    assert TEST_VIDEO.exists(), f"Test video not found at {TEST_VIDEO}"
    return TEST_VIDEO

@pytest.fixture(scope="session") # Run once per session
def detected_shots_json(tmp_path_factory, test_video_exists):
    """Fixture to run detect-shots once and provide the output JSON path."""
    # test_video_exists fixture ensures video is present
    video_path = test_video_exists
    if not video_path.is_file():
        pytest.fail(f"Test video not found at {video_path}. Please ensure it exists.")

    # Use a session-scoped temp dir for the output
    output_dir = tmp_path_factory.mktemp("detect_shots_output")
    output_json = output_dir / "detected_shots.json"

    # Set environment variable for MPS fallback - needed for this fixture run
    # Note: monkeypatch isn't directly usable in session scope fixtures easily,
    # rely on it being set externally for now or use --device cpu.
    args = [
        "--device", "cpu", # Use CPU for fixture consistency
        "video", "detect-shots",
        str(video_path),
        "-o", str(output_json)
    ]

    original_argv = sys.argv
    sys.argv = ["avtools"] + args
    print(f"\nRunning detect-shots fixture with args: {args}")

    try:
        # Patch sys.exit to prevent test termination
        with patch('sys.exit') as mock_exit:
            avtools_main()
            # Optional: Assert successful exit if needed
            # mock_exit.assert_called_once_with(0)
        assert output_json.exists()
        with open(output_json, 'r') as f:
            data = json.load(f)
    except Exception as e:
        pytest.fail(f"Fixture: An unexpected error occurred during avtools_main execution for detect-shots: {e}")
    finally:
        sys.argv = original_argv

    if not output_json.is_file():
        pytest.fail(f"Fixture: detect-shots did not create output JSON: {output_json}")

    print(f"Detect-shots fixture generated: {output_json}")
    return output_json

# --- Fixture for Dummy Tag Data ---
@pytest.fixture(scope="session")
def dummy_tags_json(tmp_path_factory):
    """Create a dummy tags JSON file for tag extraction tests."""
    tags_dir = tmp_path_factory.mktemp("dummy_tags")
    tags_json_path = tags_dir / "dummy_tags.json"
    # Example structure - adjust based on actual expected input format
    dummy_data = {
        "frame_tags": {
            "10": ["tagA", "tagB"],
            "100": ["tagC"]
        },
        "shot_tags": {
            "0": ["scene1", "intro"], # Assuming shot index or ID as key
            "1": ["scene2"]
        }
    }
    with open(tags_json_path, 'w') as f:
        json.dump(dummy_data, f)
    return tags_json_path

# Fixture to create a cache entry for the test video
@pytest.fixture
def video_cache_entry(tmp_path, test_video_exists, detected_shots_json):
    """Runs cache-frames to ensure a cache entry exists."""
    video_path = str(test_video_exists)
    shots_json_path = str(detected_shots_json)
    # 1. Calculate video hash
    video_hash = get_video_hash(video_path)
    # 2. Get the specific video cache directory using the hash
    video_cache_subdir = get_video_dir(video_hash)

    # Clear any previous cache just in case
    if video_cache_subdir.exists():
        shutil.rmtree(video_cache_subdir)

    args = ["video"]
    args.extend(["cache-frames", video_path, shots_json_path])
    print(f"Running cache-frames command: {' '.join(args)}")
    original_argv = sys.argv
    sys.argv = ["avtools"] + args
    try:
        # Patch sys.exit during fixture setup
        with patch('sys.exit') as mock_fixture_exit:
            avtools_main()
            # Check if exit was called with 0 (success)
            if mock_fixture_exit.call_args:
                assert mock_fixture_exit.call_args[0][0] == 0

        assert video_cache_subdir.exists(), f"Cache directory {video_cache_subdir} was not created."
        # Return the path for cleanup or verification
        yield video_path, video_cache_subdir, video_hash
    finally:
        sys.argv = original_argv
        # Optional: Clean up cache after test, though clear test handles this
        # if cache_dir.exists():
        #     shutil.rmtree(cache_dir)

# --- Tests ---

def test_detect_shots_cli_output(detected_shots_json):
    """Test the content of the JSON generated by detect-shots."""
    output_json = detected_shots_json # Get path from fixture
    assert output_json.is_file(), f"Output JSON file not created by fixture: {output_json}"

    # Check if output file is valid JSON and not empty
    with open(output_json, 'r') as f:
        try:
            data = json.load(f)
            assert isinstance(data, dict), "Output is not a JSON object"
            assert "shots" in data, "'shots' key missing in output JSON"
            assert isinstance(data["shots"], list), "'shots' is not a list"
            # Check for at least one shot (adjust if Rickroll might have 0)
            assert len(data["shots"]) >= 0, "No shots detected or recorded in JSON"
            if len(data["shots"]) > 0:
                first_shot = data["shots"][0]
                assert "start_frame" in first_shot # Check for start_frame
                assert "end_frame" in first_shot # Check for end_frame
                assert "fps" in data # Check fps key exists
        except json.JSONDecodeError:
            pytest.fail(f"Output file is not valid JSON: {output_json}")

@pytest.mark.env(PYTORCH_ENABLE_MPS_FALLBACK="1")
def test_detect_shots_cli_options(test_video_exists, tmp_path):
    """Test the 'video detect-shots' command with custom threshold and output."""
    video_path = test_video_exists
    custom_output_path = tmp_path / "custom_shots.json"

    detect_args = [
        "video",
        "detect-shots",
        str(video_path),
        "--threshold", "0.6",
        "--output", str(custom_output_path)
    ]

    print(f"Running detect-shots with options: {' '.join(detect_args)}")
    original_argv = sys.argv
    return_code = 1 # Default to failure

    try:
        sys.argv = ["avtools"] + detect_args
        with patch('sys.exit') as mock_exit:
            avtools_main()
            if mock_exit.call_args:
                return_code = mock_exit.call_args[0][0]
            else:
                return_code = 0
    except Exception as e:
        pytest.fail(f"detect-shots command with options raised unexpected exception: {e}")
    finally:
        sys.argv = original_argv

    assert return_code == 0, f"detect-shots command with options failed with exit code {return_code}"
    assert custom_output_path.exists(), f"Custom output file {custom_output_path} was not created."
    # Optional: Load JSON and check content/number of shots
    with open(custom_output_path) as f:
        data = json.load(f)
        assert "shots" in data
        assert isinstance(data["shots"], list)
        assert "fps" in data

def test_extract_shots_cli(tmp_path, detected_shots_json):
    """Test running the 'extract-shots' command using detected shots JSON."""
    input_json = detected_shots_json # Get path from fixture
    output_dir = tmp_path / "extracted_shots"

    args = [
        # No top-level options needed for extract-shots currently
        "video", "extract-shots",
        str(input_json),
        str(TEST_VIDEO),
        "-o", str(output_dir)
    ]

    original_argv = sys.argv
    sys.argv = ["avtools"] + args
    print(f"\nRunning extract-shots test with args: {args}")

    try:
        avtools_main()
    except SystemExit as e:
        if e.code != 0:
            pytest.fail(f"avtools_main failed extract-shots with SystemExit code {e.code} for args: {args}")
    except Exception as e:
        pytest.fail(f"An unexpected error occurred during avtools_main execution for extract-shots: {e}")
    finally:
        sys.argv = original_argv

    # --- Post-execution checks ---
    assert output_dir.is_dir(), f"Output directory not created: {output_dir}"

    # Check if any video files were created in the output directory
    output_files = list(output_dir.glob("shot_*.mp4")) # Assuming default naming convention
    assert len(output_files) > 0, f"No output video files found in {output_dir}"
    print(f"Found {len(output_files)} output shot files.")

    # Optional: More detailed check - count files match number of shots in JSON
    with open(input_json, 'r') as f:
        shots_data = json.load(f)
        num_shots = len(shots_data.get("shots", []))
        # Allow for possibility of zero shots if the video has none
        assert len(output_files) == num_shots, \
               f"Number of extracted shots ({len(output_files)}) does not match shots in JSON ({num_shots})"

# --- Additional Video Command Tests ---

def test_video_fcpxml_cli(tmp_path, detected_shots_json):
    """Test the 'video fcpxml' command."""
    shots_json_path = str(detected_shots_json)
    output_fcpxml_path = tmp_path / "output.fcpxml"

    # Run fcpxml command
    args = ["video"]
    args.extend(["fcpxml", shots_json_path, "-o", str(output_fcpxml_path)])
    print(f"Running fcpxml command: {' '.join(args)}")
    original_argv = sys.argv
    sys.argv = ["avtools"] + args
    return_code = 1 # Default to fail
    try:
        with patch('sys.exit') as mock_exit:
            avtools_main()
            if mock_exit.call_args:
                return_code = mock_exit.call_args[0][0]
            else:
                # Assume success if exit wasn't explicitly called (though it should be)
                return_code = 0
    finally:
        sys.argv = original_argv

    assert return_code == 0, f"fcpxml command failed with exit code {return_code}"
    # Assert output file exists
    assert output_fcpxml_path.exists(), f"Output FCPXML file {output_fcpxml_path} was not created."

    # Basic content check
    with open(output_fcpxml_path, 'r') as f:
        content = f.read()
    assert "<fcpxml version=" in content, """FCPXML root element not found."""
    assert "<asset-clip name=" in content, """Asset clip elements not found in FCPXML."""
    
# test_cache_frames_cli, test_extract_frames_to_dir_cli, test_cache_clear_cli, and test_cache_list_cli
# have been moved to tests/cli/test_cache_commands.py

def test_detect_shots_cli_invalid_video(tmp_path):
    """Test running detect-shots with a non-existent video file."""
    non_existent_video = tmp_path / "not_a_real_video.mp4"
    output_json = tmp_path / "output_should_not_be_created.json"

    args = [
        "--device", "cpu",
        "video", "detect-shots",
        str(non_existent_video),
        "-o", str(output_json)
    ]

    original_argv = sys.argv
    exit_code = None
    try:
        sys.argv = ["avtools"] + args
        print(f"\nRunning detect-shots (invalid input) test with args: {args}")
        # Expecting a failure, potentially SystemExit or other Exception
        avtools_main()
    except FileNotFoundError:
        # If the underlying function raises FileNotFoundError directly
        print("Caught expected FileNotFoundError")
        exit_code = -1 # Use a specific value to indicate caught exception
    except SystemExit as e:
        print(f"Caught SystemExit with code: {e.code}")
        exit_code = e.code
    except Exception as e:
        # Catch any other unexpected exceptions
        pytest.fail(f"detect-shots with invalid input raised unexpected Exception: {e}")
    finally:
        sys.argv = original_argv

    # Assert that the command failed as expected
    assert exit_code != 0, "Command should have failed (non-zero exit or exception) for non-existent video"
    # Assert that the output file was NOT created
    assert not output_json.exists(), f"Output JSON {output_json} should not have been created for invalid input"
    print("Detect-shots failed gracefully for non-existent video as expected.")

def test_cache_list_cli(video_cache_entry):
    """Test the 'video cache-list' command."""
    video_path, video_cache_subdir, video_hash = video_cache_entry

    # Run cache-list using subprocess to capture output
    process = subprocess.run(
        [sys.executable, "-m", "avtools.cli.main", "video", "cache-list"],
        capture_output=True,
        text=True,
        check=False # Don't check exit code here, check output
    )

    print(f"cache-list stdout:\n{process.stdout}")
    print(f"cache-list stderr:\n{process.stderr}")
    assert process.returncode == 0
    # Check that the video hash is present in stderr (logged output)
    assert video_hash in process.stderr

def test_cache_clear_cli(video_cache_entry):
    """Test the 'video cache-clear' command."""
    video_path, video_cache_subdir, video_hash = video_cache_entry

    # Ensure cache exists before clearing
    assert video_cache_subdir.exists(), f"Cache directory {video_cache_subdir} should exist before clearing."

    # Run cache-clear command
    args = ["video"]
    args.extend(["cache-clear", "--video", video_path])
    print(f"Running cache-clear command: {' '.join(args)}")
    original_argv = sys.argv
    sys.argv = ["avtools"] + args
    return_code = 1 # Default to fail
    try:
        # Need to wrap main call to get return code
        # Patch sys.exit here as well
        with patch('sys.exit') as mock_test_exit:
            avtools_main()
            # Check the intended exit code from the mock
            if mock_test_exit.call_args:
                return_code = mock_test_exit.call_args[0][0]
            else:
                # If sys.exit wasn't called, assume success (code 0)
                # although main() should ideally always exit.
                return_code = 0
    finally:
        sys.argv = original_argv

    assert return_code == 0, f"cache-clear command failed with exit code {return_code}"
    # Assert cache directory is now removed
    assert not video_cache_subdir.exists(), f"Cache directory {video_cache_subdir} should not exist after clearing."

# Add more tests here for other video commands like cache-frames etc. 