name: Python CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
        # Install Cython first
        pip install Cython>=0.29.24
        
        # Install PyTorch separately
        pip install torch>=2.0.0 torchvision>=0.21.0
        
        # Install madmom from source
        pip install git+https://github.com/CPJKU/madmom.git@main#egg=madmom
        
        # Skip natten for now to get CI passing
        # pip install natten==0.14.6
        
        # Install remaining dependencies
        grep -v "^madmom" requirements.txt | grep -v "^torch" | grep -v "^torchvision" | grep -v "^natten" | grep -v "^Cython" > filtered_requirements.txt
        pip install -r filtered_requirements.txt
        pip install -r requirements-dev.txt
        
        # Install the package in development mode
        pip install -e .

    - name: Run Ruff Linter
      run: |
        ruff check .

    - name: Build MkDocs Documentation
      run: |
        mkdocs build --strict # Fail CI on warnings/errors

    - name: Run Pytest
      run: |
        pytest --cov=avtools --cov-report=xml --cov-fail-under=80 tests/
      env:
        PYTORCH_ENABLE_MPS_FALLBACK: 1 # Ensure MPS fallback for tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Optional: Use repository secret if needed
        slug: allenday/avtools # Optional: Explicitly specify repository slug
